name: Deploy to WordPress.org
on:
  push:
    tags:
    - "*"
jobs:
  tag:
    name: Build plugin and deploy to WordPress.org
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - name: Setup PHP
      uses: shivammathur/setup-php@v2

    - name: Install Node.js via NVM
      uses: irby/setup-node-nvm@master

    - name: Install Javascript dependencies
      run: |
        npm install

    - name: Package
      run: |
        ./scripts/package.sh

    - name: Remove zip file
      run: |
        rm common-knowledge-join-flow.zip

    - name: WordPress Plugin Deploy
      uses: 10up/action-wordpress-plugin-deploy@stable
      env:
        SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
        SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
        SLUG: common-knowledge-join-flow
        BUILD_DIR: dist/common-knowledge-join-flow